"""add_storage_path_to_inventory_items

Revision ID: ae08e21a2513
Revises: 8c10db25573a
Create Date: 2025-10-19 00:46:27.129281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae08e21a2513'
down_revision = '8c10db25573a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'storage_path')
    # ### end Alembic commands ###